### ISSUE TITLE
Add this to NPM?

### ISSUE THREAD

**Issue by sidonaldson** [WebsiteBeaver/facebook-api-javascript-sdk-get-all-albums-and-photos#1]
Looks fit for purpose. Why don't you open it up as a package?

**Comment by D-Marc1** [comment]
Good idea, I'll add it to NPM this weekend. I'll add JSDoc to it as well.

**Comment by D-Marc1** [comment]
Don't worry, I haven't forgotten about this. I just finished polishing the code, adding stuff to it and documenting it with examples. Unfortunately, Facebook revoked my `user_photos` permissions, because I forgot to resubmit it, so I'm going to reapply so I can fully test out all of my changes and create an official version 1 I'll submit to NPM.

**Comment by sidonaldson** [comment]
@D-Marc1 want me to be a contributor? Happy to review and finesse

**Comment by D-Marc1** [comment]
I just updated the repo to convert to promises, add JSDoc with examples, add a `getProfilePicture()` method and reorganize the file structure.  That would be awesome if you could review my changes. You can simply download the repo with my demo and change the `addId` on **index.html**. I couldn't figure out how to document the public properties I used, but I'll look into that as well.

If everything looks fine, I'll create an official version 1 and add it to NPM.

**Comment by D-Marc1** [comment]
It's on NPM now https://www.npmjs.com/package/facebook-javascript-all-photos.
